dependencies:
- name: pairing-adapter
  condition: pairing-adapter.enabled
- name: external-services-mock
  condition: global.externalServicesMock.enabled
- name: prometheus-postgres-exporter
  condition: global.metrics.enabled
- name: system-broker
  condition: global.system_broker.enabled
- name: operations-controller
  condition: global.operations_controller.enabled
