{{- if eq .Values.global.externalServicesMock.auditlog true }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.auditlog.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{ .Values.global.auditlog.secret.clientIdKey }}: {{ "client_id" | b64enc | quote }}
  {{ .Values.global.auditlog.secret.clientSecretKey }}: {{ "client_secret" | b64enc | quote }}
  {{ .Values.global.auditlog.secret.urlKey }}: {{ printf "http://compass-external-services-mock.%s.svc.cluster.local:%s/secured" .Release.Namespace (.Values.service.port | toString) | b64enc | quote }}
{{end}}
{{- if eq .Values.global.externalCertConfiguration.secrets.externalCertSvcSecret.manage true }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.externalCertConfiguration.secrets.externalCertSvcSecret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{ .Values.global.externalCertConfiguration.secrets.externalCertSvcSecret.clientIdKey }}: {{ "client_id" | b64enc | quote }}
  {{ .Values.global.externalCertConfiguration.secrets.externalCertSvcSecret.clientSecretKey }}: {{ "client_secret" | b64enc | quote }}
  {{ .Values.global.externalCertConfiguration.secrets.externalCertSvcSecret.oauthUrlKey }}: {{ printf "http://compass-external-services-mock.%s.svc.cluster.local:%s" .Release.Namespace (.Values.service.port | toString) | b64enc | quote }}
  {{ .Values.global.externalCertConfiguration.secrets.externalCertSvcSecret.csrEndpointKey }}: {{ "http://compass-external-services-mock.compass-system.svc.cluster.local:8080" | b64enc | quote }}
{{- end }}
{{- if eq .Values.global.externalCertConfiguration.secrets.externalCertSvcSecret.manage true }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.tests.externalServicesMock.oauthSecretName }} # TODO:: check the namespace and unify with the secrets below
  namespace: compass-system
type: Opaque
data:
  {{ .Values.global.tests.externalServicesMock.clientIdKey }}: {{ "client_id" | b64enc | quote }}
  {{ .Values.global.tests.externalServicesMock.clientSecretKey }}: {{ "client_secret" | b64enc | quote }}
  {{ .Values.global.tests.externalServicesMock.oauthUrlKey }}: {{ printf "http://compass-external-services-mock.compass-system.svc.cluster.local:8080" | b64enc | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.externalServicesMock.oauthSecretName }}
  namespace: compass-system
type: Opaque
data:
  client-id: {{ "client_id" | b64enc | quote }}
  client-secret: {{ "client_secret" | b64enc | quote }}
  url: {{ printf "http://compass-external-services-mock.%s.svc.cluster.local:%s" .Release.Namespace (.Values.service.port | toString) | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.externalServicesMock.oauthSecretName }}
  namespace: kyma-system
type: Opaque
data:
  client-id: {{ "client_id" | b64enc | quote }}
  client-secret: {{ "client_secret" | b64enc | quote }}
  url: {{ printf "http://compass-external-services-mock.%s.svc.cluster.local:%s" .Release.Namespace (.Values.service.port | toString) | b64enc | quote }}
