{{- if eq .Values.global.externalServicesMock.auditlog.applyMockConfiguration true }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.auditlog.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{ .Values.global.auditlog.secret.clientIdKey }}: {{ "client_id" | b64enc | quote }}
  {{ .Values.global.auditlog.secret.clientSecretKey }}: {{ "client_secret" | b64enc | quote }}
  {{ .Values.global.auditlog.secret.urlKey }}: {{ printf "https://%s.%s:%s" .Values.global.externalServicesMock.certSecuredHost .Values.global.ingress.domainName (.Values.service.certPort | toString) | b64enc | quote }}
  {{ .Values.global.auditlog.secret.clientCertKey }}: {{ .Values.global.connector.caCertificate | b64enc | quote }}
  {{ .Values.global.auditlog.secret.clientKeyKey }}: {{ .Values.global.connector.caKey | b64enc | quote }}
{{end}}
{{- if eq .Values.global.externalCertConfiguration.secrets.externalCertSvcSecret.manage true }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.externalCertConfiguration.secrets.externalCertSvcSecret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{ .Values.global.externalCertConfiguration.secrets.externalCertSvcSecret.clientIdKey }}: {{ "client_id" | b64enc | quote }}
  {{ .Values.global.externalCertConfiguration.secrets.externalCertSvcSecret.clientSecretKey }}: {{ "client_secret" | b64enc | quote }}
  {{ .Values.global.externalCertConfiguration.secrets.externalCertSvcSecret.oauthUrlKey }}: {{ printf "https://%s.%s:%s" .Values.global.externalServicesMock.certSecuredHost .Values.global.ingress.domainName (.Values.service.certPort | toString) | b64enc | quote }}
  {{ .Values.global.externalCertConfiguration.secrets.externalCertSvcSecret.csrEndpointKey }}: {{ "http://compass-external-services-mock.compass-system.svc.cluster.local:8080" | b64enc | quote }}
  {{ .Values.global.externalCertConfiguration.secrets.externalCertSvcSecret.clientCert }}: {{ .Values.global.connector.caCertificate | b64enc | quote }}
  {{ .Values.global.externalCertConfiguration.secrets.externalCertSvcSecret.clientKey }}: {{ .Values.global.connector.caKey | b64enc | quote}}
{{- end }}
{{- if eq .Values.global.externalServicesMock.oauthSecret.manage true }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.externalServicesMock.oauthSecret.name }}
  namespace: compass-system
type: Opaque
data:
  cert: {{ "cert" | b64enc | quote }}
  key: {{ "key" | b64enc | quote }}
  {{ .Values.global.externalServicesMock.oauthSecret.clientIdKey }}: {{ "client_id" | b64enc | quote }}
  {{ .Values.global.externalServicesMock.oauthSecret.clientSecretKey }}: {{ "client_secret" | b64enc | quote }}
  {{ .Values.global.externalServicesMock.oauthSecret.oauthUrlKey }}: {{ printf "http://compass-external-services-mock.%s.svc.cluster.local:%s" .Release.Namespace (.Values.service.port | toString) | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.externalServicesMock.oauthSecret.name }}
  namespace: kyma-system
type: Opaque
data:
  cert: {{ "cert" | b64enc | quote }}
  key: {{ "key" | b64enc | quote }}
  {{ .Values.global.externalServicesMock.oauthSecret.clientIdKey }}: {{ "client_id" | b64enc | quote }}
  {{ .Values.global.externalServicesMock.oauthSecret.clientSecretKey }}: {{ "client_secret" | b64enc | quote }}
  {{ .Values.global.externalServicesMock.oauthSecret.oauthUrlKey }}: {{ printf "http://compass-external-services-mock.%s.svc.cluster.local:%s" .Release.Namespace (.Values.service.port | toString) | b64enc | quote }}
{{- end }}
{{- if eq .Values.global.tests.subscription.oauthSecret.manage true }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.tests.subscription.oauthSecret.name }}
  namespace: kyma-system
type: Opaque
data:
  {{ .Values.global.tests.subscription.oauthSecret.clientIdKey }}: {{ "client_id" | b64enc | quote }}
  {{ .Values.global.tests.subscription.oauthSecret.clientSecretKey }}: {{ "client_secret" | b64enc | quote }}
  {{ .Values.global.tests.subscription.oauthSecret.oauthUrlKey }}: {{ printf "http://compass-external-services-mock.%s.svc.cluster.local:%s" .Release.Namespace (.Values.service.port | toString) | b64enc | quote }}
{{- end }}
