required = [
    "golang.org/x/tools/cmd/goimports",
    "github.com/kisielk/errcheck",
]

[[constraint]]
  name = "github.com/kisielk/errcheck"
  revision = "e14f8d59a22d460d56c5ee92507cd94c78fbf274"

[[constraint]]
  name = "github.com/99designs/gqlgen"
  version = "0.9.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.2"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.15.2"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.15.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.15.2"

[[override]]
  name = "k8s.io/kubernetes"
  version = "kubernetes-1.15.2"

[prune]
  go-tests = true
  unused-packages = true
