required = [
    "golang.org/x/tools/cmd/goimports",
    "github.com/kisielk/errcheck",
]

[[constraint]]
  name = "github.com/kisielk/errcheck"
  revision = "e14f8d59a22d460d56c5ee92507cd94c78fbf274"

[[constraint]]
  name = "github.com/99designs/gqlgen"
  version = "0.9.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.2"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.14.7"

[[constraint]]
  name = "github.com/gocraft/dbr"
  version = "2.6"

[[override]]
  name = "k8s.io/kubernetes"
  version = "kubernetes-1.14.7"

[[override]]
  name = "github.com/kyma-incubator/hydroform"
  source = "github.com/Maladie/hydroform"
  branch = "azure"

[prune]
  go-tests = true
  unused-packages = true
