required = [
    "golang.org/x/tools/cmd/goimports",
    "github.com/kisielk/errcheck",
]

[[constraint]]
  name = "github.com/kisielk/errcheck"
  revision = "e14f8d59a22d460d56c5ee92507cd94c78fbf274"

[[constraint]]
  name = "github.com/99designs/gqlgen"
  version = "0.9.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.2"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.15.2"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.15.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.15.2"

[[override]]
  name = "k8s.io/kubernetes"
  version = "kubernetes-1.15.2"

[[constraint]]
  name = "github.com/gocraft/dbr"
  version = "2.6"

[[constraint]]
  name = "github.com/kyma-incubator/hydroform"
  revision = "b358b7f6a333db6eb56d6315140b072da7bbe928"

[[override]]
  name = "github.com/cpuguy83/go-md2man"
  version = "1.0.10"

[[override]]
  name = "github.com/kyma-incubator/terraform-provider-gardener"
  revision = "100e0f88e4cff7ccc284c6c4322a3a09b50b68bf"

[prune]
  go-tests = true
  unused-packages = true
