deployment:
  replicaCount: 1
  image:
    pullPolicy: Never
  resources: {}
  args:
    containerPort: 5001
  securityContext: # Set on container level
    runAsUser: 2000
    allowPrivilegeEscalation: false
  allowJWTSigningNone: true # To run integration tests, it has to be enabled
  strategy: {} # Read more: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
  nodeSelector: {}

metrics:
  port: 5002