{{if and (eq .Values.global.externalServicesMock.enabled true) (eq .Values.gateway.gateway.auditlog.enabled true) (eq .Values.global.externalServicesMock.auditlog true) }}
apiVersion: "testing.kyma-project.io/v1alpha1"
kind: TestDefinition
metadata:
  name: {{ .Chart.Name }}-gateway-external-services-integration
  labels:
    app: {{ .Chart.Name }}-e2e-tests
    app.kubernetes.io/name: {{ .Chart.Name }}-e2e-tests
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  namespace: kyma-system
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: {{ .Chart.Name }}-gateway-external-services-integration-tests
    spec:
      {{ if .Values.global.isLocalEnv }}
      hostAliases:
        - ip: {{ .Values.global.minikubeIP }}
          hostnames:
            - "{{ .Values.global.gateway.tls.host }}.{{ .Values.global.ingress.domainName }}"
            - "dex.{{ .Values.global.ingress.domainName }}"
            - "oauth2.{{ .Values.global.ingress.domainName }}"
            - "{{ .Values.global.gateway.tls.secure.oauth.host }}.{{ .Values.global.ingress.domainName }}"
            - "{{ .Values.global.gateway.mtls.host }}.{{ .Values.global.ingress.domainName }}"
            - "compass-external-services-mock.compass-system.svc.cluster.local"
      {{ end }}
      containers:
        - name: auditlog-tests
          image: {{ .Values.global.images.containerRegistry.path }}/{{ .Values.global.images.tests.director.dir }}compass-director-tests:{{ .Values.global.images.tests.director.version }}
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args: ["-c", "/external-services-mock-integration.test -test.v; exit_code=$?; curl -XPOST http://127.0.0.1:15020/quitquitquit; sleep 4; exit $exit_code;"]
          env:
            - name: DIRECTOR_URL
              value: "https://{{ .Values.global.gateway.tls.host }}.{{ .Values.global.ingress.domainName }}{{ .Values.global.director.prefix }}"
            - name: DIRECTOR_HEALTHZ_URL
              value: "http://compass-director.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.global.director.port }}/healthz"
            - name: ALL_SCOPES
              value: "{{ .Values.global.director.tests.scopes }}"
            - name: USER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: admin-user
                  key: email
            - name: USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: admin-user
                  key: password
            - name: APP_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.auditlog.secretName }}
                  key: auditlog-client-id
            - name: APP_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.auditlog.secretName }}
                  key: auditlog-client-secret
            - name: BASIC_CREDENTIALS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.testCredentials.secretName }}
                  key: username
            - name: BASIC_CREDENTIALS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.testCredentials.secretName }}
                  key: password
            - name: DEFAULT_TENANT
              value: "{{.Values.global.defaultTenant}}"
            - name: DOMAIN
              value: "{{ .Values.global.ingress.domainName }}"
            - name: GATEWAY_OAUTH20_SUBDOMAIN
              value: "{{ .Values.global.gateway.tls.secure.oauth.host }}"
            - name: GATEWAY_JWT_SUBDOMAIN
              value: "{{ .Values.global.gateway.tls.host }}"
            - name: GATEWAY_CLIENT_CERTS_SUBDOMAIN
              value: "{{ .Values.global.gateway.mtls.host }}"
            - name: EXTERNAL_SERVICES_MOCK_BASE_URL
              value: "http://compass-external-services-mock.{{ .Release.Namespace }}.svc.cluster.local:8080/"
      restartPolicy: Never
  {{end}}
