apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: {{ .Chart.Name }}-oathkeeper-header-rewrite
  namespace: {{ .Values.global.rewriteFilters.namespace }}
spec:
  workloadSelector:
    labels:
      app.kubernetes.io/name: {{ .Values.global.rewriteFilters.workloadLabel }}
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
              subFilter:
                name: "envoy.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.lua
          {{- if .Capabilities.APIVersions.Has "security.istio.io/v1beta1/PeerAuthentication" }}
          typed_config:
            "@type": "type.googleapis.com/envoy.config.filter.http.lua.v2.Lua"
          {{- else }}
          config:
          {{- end }} 
            inlineCode: |
              function envoy_on_request(request_handle)
                local headers = request_handle:headers()
                local xForwardedClientCert = headers:get("X-Forwarded-Client-Cert")

                headers:add("{{ .Values.global.rewriteFilters.certificateDataHeader }}",xForwardedClientCert)
              end