{{ if .Values.global.disableLegacyConnectivity }}
apiVersion: v1
kind: ConfigMap
{{ $configmapName := .Values.global.connector.revocation.configmap.name }}
{{ $configmapNamespace := (tpl .Values.global.connector.revocation.configmap.namespace .) }}
metadata:
  name: {{ $configmapName }}
  namespace: {{ $configmapNamespace }}
  labels:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ $configmap := (lookup "v1" "ConfigMap" $configmapNamespace $configmapName) }}
{{ if empty $configmap }}
data:
{{ else }}
data:
{{ toYaml $configmap.data | indent 2}}
{{ end }}
{{ end }}
