{{- if (include "postgresql.createSecret" .) }}
{{- $user := (include "postgresql.username" . | b64enc | quote) -}}
{{- $pass := (include "postgresql.password" . | b64enc | quote) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "postgresql.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "postgresql.name" . }}
    chart: {{ template "postgresql.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  annotations:
    "helm.sh/hook": "pre-install" # Modified
    "helm.sh/hook-delete-policy": "before-hook-creation" # Modified
type: Opaque
data:
  postgresql-director-db-name: {{ .Values.global.database.embedded.director.name | b64enc | quote }} # Modified
  postgresql-director-username: {{ $user }} # Modified
  postgresql-director-password: {{ $pass }}
  postgresql-serviceName: {{ include "postgresql.fullname" . | b64enc | quote }} # Modified
  postgresql-servicePort: {{ include "postgresql.port" . | b64enc | quote }} # Modified
  postgresql-sslMode: {{ "disable" | b64enc | quote }} # Modified
  {{- if .Values.replication.enabled }}
  postgresql-replication-password: {{ include "postgresql.replication.password" . | b64enc | quote }}
  {{- end }}
  postgresql-username: {{ include "postgresql.username" . | b64enc | quote }} #TODO remove after migration to separate user will be done
  postgresql-password: {{ include "postgresql.password" . | b64enc | quote }} #TODO remove after migration to separate user will be done
  postgresql-directorDatabaseName: {{ .Values.global.database.embedded.directorDBName | b64enc | quote }} #TODO remove after migration to separate user will be done
{{- end -}}