apiVersion: v1
kind: ConfigMap
metadata:
  name: compass-overrides
  namespace: compass-installer
  labels:
    installer: overrides
    component: compass
    kyma-project.io/installation: ""
data:
  # Kyma installer was ran with disabled legacy connectivity which resulted in creating this secret in kyma-integration
  global.connector.secrets.ca.name: "connector-service-app-ca"
  global.connector.secrets.ca.namespace: "kyma-integration"

  # Connect runtime agent installed by Kyma intaller to compass (setup job is ran as part of compass installer)
  global.agentPreconfiguration: "true"
  global.hydrator.http.client.skipSSLValidation: "true"