global:
  tests:
    namespace: kyma-system
  database:
    embedded:
      director:
        name: "postgres"
      ias_adapter:
        name: "postgres2"
      directorDBName: "postgres"
      # Database create on initial deployment; used by `install-ory.sh
      hydra:
        name: "hydra"

postgresql:
  # Admin username; used by `install-ory.sh`
  postgresqlUsername: postgres
  # Admin user password; used by `install-ory.sh
  postgresqlPassword: postgres
