apiVersion: "testing.kyma-project.io/v1alpha1"
kind: TestDefinition
metadata:
  name: {{ .Chart.Name }}-bench-ord-service
  labels:
    benchmark: "true" # This is needed to differentiate benchmarks of regular tests
    app: {{ .Chart.Name }}-ord-service-bench-app
    release: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}-ord-service-bench
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  namespace: {{ .Values.global.tests.namespace }}
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: {{ .Chart.Name }}-ord-service-bench-app
    spec:
      nodeSelector:
        benchmark: "true" # This guarantees that benchmark tests will be executed on one and the same node. The gke-benchamrk job adds the benchmark=true label to the node with the lowest cpu load.
      containers:
        - name: ord-service-bench # This should be unique across all benchmark containers.
          image: {{ .Values.global.images.containerRegistry.path }}/{{ .Values.global.images.e2e_tests.dir }}compass-tests:{{ .Values.global.images.e2e_tests.version }}
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args: ["-c", "./ord-service.bench -test.v -test.bench=. -test.benchtime 5s -test.count 5; exit_code=$?; echo code is $exit_code; echo 'killing pilot-agent...'; curl -XPOST http://127.0.0.1:15020/quitquitquit; sleep 4; exit $exit_code;"]
          restartPolicy: Never
          env:
            - name: ORD_SERVICE_URL
              value: "https://{{ .Values.global.gateway.tls.host }}.{{ .Values.global.ingress.domainName }}{{ .Values.global.ordService.prefix }}"
            - name: ORD_SERVICE_HEALTHZ_URL
              value: "{{ .Values.global.tests.ordServiceFQDN }}:{{ .Values.global.director.graphql.external.port }}/actuator/health"
            - name: ORD_SERVICE_DEFAULT_RESPONSE_TYPE
              value: {{ .Values.global.ordService.defaultResponseType }}
            - name: DIRECTOR_URL
              value: "https://{{ .Values.global.gateway.tls.host }}.{{ .Values.global.ingress.domainName }}{{ .Values.global.director.prefix }}"
            - name: APP_DB_USER
              valueFrom:
                secretKeyRef:
                  name: compass-postgresql
                  key: postgresql-director-username
            - name: APP_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: compass-postgresql
                  key: postgresql-director-password
            - name: APP_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: compass-postgresql
                  key: postgresql-serviceName
            - name: APP_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: compass-postgresql
                  key: postgresql-servicePort
            - name: APP_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: compass-postgresql
                  key: postgresql-director-db-name
            - name: APP_DB_SSL
              valueFrom:
                secretKeyRef:
                  name: compass-postgresql
                  key: postgresql-sslMode
            - name: USER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: admin-user
                  key: email
            - name: USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: admin-user
                  key: password
            - name: DOMAIN
              value: "{{ .Values.global.ingress.domainName }}"
            - name: APP_IS_WITH_TOKEN
              value: "{{.Values.global.tests.token.server.enabled}}"
            - name: APP_ADDRESS
              value: "0.0.0.0:{{.Values.global.tests.token.server.port}}"