apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    control-plane: controller-manager
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.manager.replicaCount }}
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        app: {{ .Chart.Name }}
        reqlimit: {{ .Values.global.istio.ingressgateway.requestPayloadSizeLimit2MBLabel }}
        release: {{ .Release.Name }}
        control-plane: controller-manager
    spec:
      {{ if .Values.global.isLocalEnv }}
      # HostAliases are used by Pod to resolve kyma.local domain
      hostAliases:
        - ip: {{ .Values.global.minikubeIP }}
          hostnames:
            # Used for calls to Director
            - "{{ .Values.global.gateway.tls.secure.internal.host }}.{{ .Values.global.ingress.domainName }}"
            - "{{ .Values.global.externalServicesMock.certSecuredHost }}.{{.Values.global.ingress.domainName}}"
      {{ end }}
      serviceAccountName: {{ template "fullname" . }}
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - env:
          - name: SERVER_METRIC_ADDRESS
            value: ":{{ .Values.metrics.port }}"
          - name: SERVER_HEALTH_ADDRESS
            value: ":{{ .Values.health.port }}"
          - name: SERVER_ENABLE_LEADER_ELECTION
            value: "true"
          - name: GRAPHQL_CLIENT_GRAPHQL_ENDPOINT
            value: "https://{{ .Values.global.gateway.tls.secure.internal.host }}.{{ .Values.global.ingress.domainName }}{{ .Values.global.director.prefix }}/graphql"
          - name: DIRECTOR_OPERATION_ENDPOINT
            value: "https://{{ .Values.global.gateway.tls.secure.internal.host }}.{{ .Values.global.ingress.domainName }}{{ .Values.global.director.operations.path }}"
          - name: HTTP_CLIENT_SKIP_SSL_VALIDATION
            value: "{{ .Values.http.client.skipSSLValidation }}"
          - name: EXTERNAL_CLIENT_CERT_SECRET
            value: "{{ .Values.global.externalCertConfiguration.secrets.externalClientCertSecret.namespace }}/{{ .Values.global.externalCertConfiguration.secrets.externalClientCertSecret.name }}"
        image: {{ .Values.global.images.containerRegistry.path }}/{{ .Values.global.images.connector.dir }}compass-operations-controller:{{ .Values.global.images.operations_controller.version }}
        name: {{ .Chart.Name }}
        ports:
          - name: metrics
            containerPort: {{ .Values.metrics.port }}
            protocol: TCP
        resources:
          limits:
            cpu: {{ .Values.manager.resources.limits.cpu }}
            memory: {{ .Values.manager.resources.limits.memory }}
          requests:
            cpu: {{ .Values.manager.resources.requests.cpu }}
            memory: {{ .Values.manager.resources.requests.memory }}
      terminationGracePeriodSeconds: 10
